# spring.security.oauth2.client:

#     provider:
#       twitter:
#         authorization-uri: 
#         token-uri: 
#         user-info-uri: h
#         user-name-attribute: id

        
#     registration:
#         google:
#             client-id: 
#             client-secret: 
#         github:
#             client-id: 
#             client-secret: 
#         twitter:
#             client-id: 
#             client-secret: 
#             redirect-uri: 
#             authorization-grant-type: authorization_code
#             scope:
#                 - tweet.read
#                 - users.read
#                 - offline.access
#             client-name: Twitter
#             provider: twitter
    
